-- Initial data, including rules-related tables and the pool_teams which have already been created

BEGIN;
    SET search_path TO poolio, public;

    -- Insert point-mappings for Goals, Assists, Goalie Wins, Shutouts. These values are predetermined by the rules of the pool
    INSERT INTO point_mappings (point_type, point_value) VALUES
        ('G', 1),
        ('A', 1),
        ('W', 2),
        ('SO', 1);

     -- Insert pool teams. Points values will be updated at launch
     INSERT INTO pool_teams (team_name) VALUES
        ('Mik Patterson'),
        ('Griffin Baxter'),
        ('Nic Courion'),
        ('Kieran Ross'),
        ('Trevor Mckeown'),
        ('Adam Kealey'),
        ('Liam Bourassa'),
        ('Sam Patterson');

    -- Insert NHL Team data from a csv file which was generated by scripts/gen_nhl_teams_csv.py
    COPY teams(espn_team_id, region, nickname, abbr, logo)
    FROM '/tmp/data/nhl_teams.csv'
    DELIMITER ','
    CSV HEADER;
COMMIT;