name: poolio_api

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8080"
    # Log rotation when log file hits 10MB
    logging:
      driver: "json-file"
      options:
        - max-size: "10m"
        - max-file: "3"
    command: npm run dev

  # Loki service for log storage
  loki:
    image: grafana/loki:3.7.2
    ports:
      - "3100:3100"
    volumes:
    - ./grafana/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  # Prometheus service for metrics storage
  prometheus:
    image: prom/prometheus:v3.11.3
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Grafana UI for metrics and logs dashboards/querying
  grafana:
   image: grafana/grafana:13.0.1
   environment:
     - GF_SECURITY_ADMIN_USER=admin
     - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
   ports:
     - 3000:3000/tcp
   entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        - name: Prometheus
          type: prometheus
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh

  # Grafana alloy for collecting logs and metrics
  alloy:
   image: grafana/alloy:v1.16.1
   privileged: true
   ports:
     - 12345:12345
   environment:
      ALLOY_DEPLOY_MODE: docker
   volumes:
      - ./grafana/config.alloy:/etc/alloy/config.alloy
      - /proc:/rootproc:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys:ro
      - /:/rootfs:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
   command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
   extra_hosts:
        - "host.docker.internal:host-gateway"
   devices:
        - /dev/kmsg